Repository ubsuny/CP1-24-HW7, pull requests merged in 2024-11, with the labels that each got.

#13 made the calculus.py and test_calculus.py
  calculus.py
  test_calculus.py
Labels: python

#19 Fixed wrong linting action and python devcontainer
  .devcontainer/python/devcontainer.json
  .github/workflows/pylint.yml
Labels: bug

#12 Create calculus.py
  calculus.py
Labels: python

#15 Completed the wrapper implementation with scipy for root-finding
  calculus.py
  test_calculus.py
Labels: Algorithm

#18 Added secant_wrapper to calculus.py for root finding task
  calculus.py
Labels: enhancement, Algorithm

#20 Create function to calculate the integral using simpson.
  calculus.py
  test_calculus.py
Labels: python, Algorithm

#26 Pure python implementation of the Trapezoidal method
  calculus.py
  test_calculus.py
Labels: Algorithm

#29 Added Pure Python Implementation of Secant Root Finding
  calculus.py
  test_calculus.py
Labels: enhancement, Algorithm

#28 Adaptive Trapezoid pure python implementation.
  calculus.py
  test_calculus.py
Labels: python, Algorithm

#23 Root-finding algorithms (bisection)
  calculus.py
Labels: python

#22 Added Scipy implementation for simpson
  calculus.py
  test_calculus.py
Labels: python, Algorithm

#27 Pytest fixture for adaptive trapezoid numpy wrapper
  test_calculus.py
Labels: Algorithm

#34 Added Pure Python implementation for Tangent algorithm
  calculus.py
Labels: Algorithm

#35 Added tests for Python implementation of Tangent
  test_calculus.py
Labels: Algorithm

#32 Finalize integration calculations and clean output formatting
  calculus.py
Labels: python

#39 Stubbed Entrypoint for Ctypes and Testing
  calculus.cpp
  calculus.dll
  calculus.py
  test_calculus.py
Labels: enhancement, python

#33 Feature and Testing simpsons rule
  test_calculus.py
  visualize integrals/cos1-x.png
  visualize integrals/cos1-x_Adaptive_Trapezoid.png
  visualize integrals/cos1-x_NumPy_Trapezoid.png
  visualize integrals/cos1-x_Pure_Python_Trapezoid.png
  visualize integrals/cos1-x_Python_Trapezoid.png
  visualize integrals/cos1-x_SciPy_Trapezoid.png
  visualize integrals/cos1-x_Simpson's_Rule.png
  visualize integrals/exp-1-x.png
  visualize integrals/exp-1-x_Adaptive_Trapezoid.png
  visualize integrals/exp-1-x_NumPy_Trapezoid.png
  visualize integrals/exp-1-x_Pure_Python_Trapezoid.png
  visualize integrals/exp-1-x_Python_Trapezoid.png
  visualize integrals/exp-1-x_SciPy_Trapezoid.png
  visualize integrals/exp-1-x_Simpson's_Rule.png
  visualize integrals/x^3+1.png
  visualize integrals/x^3+1_Adaptive_Trapezoid.png
  visualize integrals/x^3+1_NumPy_Trapezoid.png
  visualize integrals/x^3+1_Pure_Python_Trapezoid.png
  visualize integrals/x^3+1_Python_Trapezoid.png
  visualize integrals/x^3+1_SciPy_Trapezoid.png
  visualize integrals/x^3+1_Simpson's_Rule.png
  visualize_integrals.py
Labels: python

#38 Integration Calculation using Adaptive Trapezoidal Method, Numpy Trapezoidal Method and the Scipy Trapezoidal Method
  calculus.py
  test_calculus.py
Labels: physics, python

#40 Find roots calculations
  Visualize roots/root_1_sinx.png
  Visualize roots/root_sinx.png
  Visualize roots/root_tanhx.png
  calculus.py
Labels: python

#44 Adaptive Trapezoid C++ implementation
  .vscode/settings.json
  calc.dll
  calculus.cpp
  calculus.py
  lib_calculus.so
  test_calculus.py
Labels: Algorithm

#41 unit test for find roots calculations
  test_calculus.py
Labels: python

#48 Added plots for visualization for three function using Adaptive Trapezoidal, Numpy Trapezoidal and Scipy Trapezoidal
  visualize integrals/(x^3) +1.png
  visualize integrals/cos(1:x).png
  visualize integrals/exp(-1:x).png
Labels: enhancement

#43 Added the C/C++ implementation for the root-finder algorithm using the tangent method
  calculus.py
  tangent_root_finder.cpp
  tangent_root_finder.dll
  test_calculus.py
Labels: Algorithm
